# Filter csv files
This notebook cleaned the labeled data and combines it with the exisitng csv files to create different csv combinations for different cases

In [1]:
import pandas as pd
import numpy as np

In [2]:
pallets = pd.read_csv("./palettes-dataframe.csv")
urls = pd.read_csv('testing2b.csv')
pallets.head()

                ID Colour 1 Colour 2 Colour 3 Episode  Frame
0  bliss_palette_0    black    black    black   Bliss      0
1  bliss_palette_1    brown    beige    brown   Bliss      1
2  bliss_palette_2    brown    brown    beige   Bliss      2
3  bliss_palette_3    beige    brown    brown   Bliss      3
4  bliss_palette_4    brown    brown    brown   Bliss      4

In [13]:
#clean pallets
pallets = pallets.rename(columns={"Colour 1": "Colour1","Colour 2":"Colour2", "Colour 3":"Colour3"})
print(pallets.head())
all_comb = set()
all_comb.update(list(pallets.Colour1.unique()))
all_comb.update(list(pallets.Colour2.unique()))
all_comb.update(list(pallets.Colour3.unique()))
# print(pallets.Colour2.unique())
all_comb #See all the possible mis lableing

                ID Colour1 Colour2 Colour3 Episode  Frame
0  bliss_palette_0   black   black   black   Bliss      0
1  bliss_palette_1   brown   beige   brown   Bliss      1
2  bliss_palette_2   brown   brown   beige   Bliss      2
3  bliss_palette_3   beige   brown   brown   Bliss      3
4  bliss_palette_4   brown   brown   brown   Bliss      4
['black' 'beige' 'brown' 'white' 'grey' 'pink' 'orange' 'green' 'purple'
 'maroon' 'lilac' 'blue' 'yellow' 'red']

{'beige',
 'black',
 'black ',
 'blue',
 'blue ',
 'brown',
 'gery',
 'green',
 'green ',
 'gret',
 'grey',
 'lilac',
 'maroon',
 'orange',
 'pink',
 'purple',
 'red',
 'white',
 'yellow'}

In [14]:
#Create mapping to update:
update_mapping = {
    'black ': 'black',
    'blue ':'blue',
    'gery':'grey',
    'green ':'green',
    'gret':'grey'
}
pallets['Colour1'] = pallets['Colour1'].replace(update_mapping)
pallets['Colour2'] = pallets['Colour2'].replace(update_mapping)
pallets['Colour3'] = pallets['Colour3'].replace(update_mapping)

In [16]:
#check all unique labels agains:

all_comb = set()
all_comb.update(list(pallets.Colour1.unique()))
all_comb.update(list(pallets.Colour2.unique()))
all_comb.update(list(pallets.Colour3.unique()))
all_comb #See all the possible mis lableing

{'beige',
 'black',
 'blue',
 'brown',
 'green',
 'grey',
 'lilac',
 'maroon',
 'orange',
 'pink',
 'purple',
 'red',
 'white',
 'yellow'}

Looks good, now we can save the csv file however we wish

In [17]:
#Check columns of urls
urls.head()

,Category,Frame,Category_val,url,0,1,2,3,4,5,6,7,8,PC1,PC2
0,Bliss,0,0,https://raw.githubusercontent.com/jf3482/DataV...,2,0,1,5,3,1,4,2,3,-0.932042,0.723724
1,Bliss,1,0,https://raw.githubusercontent.com/jf3482/DataV...,86,54,41,210,157,126,162,105,78,-1.233678,-0.583984
2,Bliss,2,0,https://raw.githubusercontent.com/jf3482/DataV...,161,105,76,86,54,40,213,159,127,1.600700,-0.999936
3,Bliss,3,0,https://raw.githubusercontent.com/jf3482/DataV...,213,159,128,87,53,39,162,105,77,1.736011,0.769814
4,Bliss,4,0,https://raw.githubusercontent.com/jf3482/DataV...,150,100,76,181,126,98,113,72,54,-0.543126,0.753430

In [20]:
# Looks like we need to rename urls colums nnames
urls = urls.rename(columns={"Category":"Episode"})
urls.head()

,Episode,Frame,Category_val,url,0,1,2,3,4,5,6,7,8,PC1,PC2
0,Bliss,0,0,https://raw.githubusercontent.com/jf3482/DataV...,2,0,1,5,3,1,4,2,3,-0.932042,0.723724
1,Bliss,1,0,https://raw.githubusercontent.com/jf3482/DataV...,86,54,41,210,157,126,162,105,78,-1.233678,-0.583984
2,Bliss,2,0,https://raw.githubusercontent.com/jf3482/DataV...,161,105,76,86,54,40,213,159,127,1.600700,-0.999936
3,Bliss,3,0,https://raw.githubusercontent.com/jf3482/DataV...,213,159,128,87,53,39,162,105,77,1.736011,0.769814
4,Bliss,4,0,https://raw.githubusercontent.com/jf3482/DataV...,150,100,76,181,126,98,113,72,54,-0.543126,0.753430

In [22]:
#Example merdge:
result_df = pd.merge(pallets, urls, on=['Episode', 'Frame'], how='inner')
result_df.head()

,ID,Colour1,Colour2,Colour3,Episode,Frame,Category_val,url,0,1,2,3,4,5,6,7,8,PC1,PC2
0,bliss_palette_0,black,black,black,Bliss,0,0,https://raw.githubusercontent.com/jf3482/DataV...,2,0,1,5,3,1,4,2,3,-0.932042,0.723724
1,bliss_palette_1,brown,beige,brown,Bliss,1,0,https://raw.githubusercontent.com/jf3482/DataV...,86,54,41,210,157,126,162,105,78,-1.233678,-0.583984
2,bliss_palette_2,brown,brown,beige,Bliss,2,0,https://raw.githubusercontent.com/jf3482/DataV...,161,105,76,86,54,40,213,159,127,1.600700,-0.999936
3,bliss_palette_3,beige,brown,brown,Bliss,3,0,https://raw.githubusercontent.com/jf3482/DataV...,213,159,128,87,53,39,162,105,77,1.736011,0.769814
4,bliss_palette_4,brown,brown,brown,Bliss,4,0,https://raw.githubusercontent.com/jf3482/DataV...,150,100,76,181,126,98,113,72,54,-0.543126,0.753430

We can save files using df.to_csv("example_file.csv" depending on what we need)